# Creating Our Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data01
  labels:
    type: local
spec:
#  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/data01"
#  claimRef:
#    name: data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data02
  labels:
    type: local
spec:
#  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/data02"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data03
  labels:
    type: local
spec:
#  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/data03"


